### ISSUE TITLE
现在有方法使用Nginx反代HTTP/2么？

### ISSUE THREAD

**Issue by Gaojianli** [ToutyRater/v2ray-guide#1]
如题，看起来可行的样子，感觉HTTP/2应该比ws好一些吧

**Comment by raidenii** [comment]
并不好
第一，nginx的代理模块不支持h2，见https://www.nginx.com/blog/http2-module-nginx/ ，试过haproxy也不行，caddy的报405错误，唯一可用的是nghttpx
第二，v2ray的h2强制要求tls，要做路径分流的话，前端的nghttpx连接后端v2ray还得再次加密，这样做毫无必要并且引入大量overhead
