### ISSUE TITLE
使用 dokodemo-door 转发含 streamSettings 的 vmess / shadowsocks 等。

### ISSUE THREAD

**Issue by TanNang** [ToutyRater/v2ray-guide#13]
具体参考：https://github.com/Equim-chan/h2s/issues/1

v2ray-core 项目下有很多关于 dokodemo-door 处理 udp 流量方法不完善的 issue，所以不建议使用这种方式通过 mkcp 传输的 vmess / shadowsocks 等。

麻烦作者在空余时间加入手册 ;)

**Comment by ToutyRater** [comment]
不是很理解你的表达。如果你是想实现使用非TCP的代理转发 (proxySettings) 的话，你引用的issue的确是个可行的方法。但是由于其中流量转发次序不容易阐述清楚，暂时没有写进白话文教程的计划

**Comment by TanNang** [comment]
意思是在 proxySettings 与 streamSettings 冲突时可以使用 dokodemo-door 来转发需要传出代理流量。

这里的冲突指的是：使用含有 HTTP 伪装的 TCP、使用 websocket、使用 mkcp / 以及使用 tls（包括在仅使用 TCP 、使用 websocket、使用 mkcp 时）


> 暂时没有写进白话文教程的计划

👌
