### ISSUE TITLE
教程里alterid的问题

### ISSUE THREAD

**Issue by linlinlin1992** [ToutyRater/v2ray-guide#18]
教程里写的是：

> "alterId": 64 // 此处的值也应当与服务器相同

> 配置中的 alterId 也是作为认证的，具体请看 V2Ray 用户手册。只要确保服务器和客户端配置文件的 alterId 相同就行了，但要注意 alterId 的值越大会使用 V2Ray 占用更多的内存。根据我的经验，对于一般用户来说，alterId 的值设为 30 到 100 之间应该是比较合适的。

>目前 alterId 服务器和客户端不一致的情况下也有可能正常连接，这不是 BUG，但还是建议保持一致。

官方文档的说法是：

> alterId：为了进一步防止被探测，一个用户可以在主 ID 的基础上，再额外生成多个 ID。这里只需要指定额外的 ID 的数量，推荐值为 32。不指定的话，默认值是 0。最大值 65535。这个值不能超过服务器端所指定的值。

我自己实测是客户端alterid低于服务器是可以正常使用的。个人理解是服务器alterid的设计是为了防止客户端值过大导致服务器内存崩溃。而小内存的客户端设备（路由器等）可以视情况调低alterid减少内存使用。

See also：
https://github.com/v2ray/v2ray-core/issues/92

**Comment by ToutyRater** [comment]
实现上本来就是可以连接的。

**Comment by VictoriaRaymond** [comment]
@linlinlin1992 从一开始就是允许的，只是最近官方文档修改了，正式把这一行为定义为特性。之前是属于“没有文档的巧合”。

另外你的理解是错的，alterid只在服务器端占用内存，在客户端不占用任何内存，即alterid=1和=1000在客户端消耗的内存是一样的。

**Comment by linlinlin1992** [comment]
@VictoriaRaymond 可是……路由器内存确实在减少alterid后降低了，难道是错觉么……
