### ISSUE TITLE
[建议] ws+tls+web在nginx配置解决可能的断流问题（仅限于闲置一段时间后）

### ISSUE THREAD

**Issue by young-zy** [ToutyRater/v2ray-guide#20]
在nginx配置下加入
proxy_read_timeout 与 proxy_send_timeout 并设置参数 
允许websocket反向代理建立长连接

从而解决在某些情况下连接处于idle状态超过默认的1分钟后被nginx关闭连接这一问题

**Comment by lifansama** [comment]
那这两个值设置成多少比较合适呢？

**Comment by young-zy** [comment]
> 那这两个值设置成多少比较合适呢？

抱歉，我似乎忘记开了这个issue（过于久远）。
后来仔细想了一想，保持长连接应该由应用软件自己实现（即发送心跳包）。所以如果设置的话只需要设置得比心跳包发送周期更长就行了。如果是由于这种原因得断流的话应该是由于长时间没有通信所以被主动切断，应该并不会影响使用。

**Comment by kmvan** [comment]
丢包率在 30～50%，什么设置都是假

**Comment by ByteArray0** [comment]
挖个坟，其实还是有影响的，比如同时连接好几台连接SSH，不能同时操作，我肯定不希望我操作这台的时候那台就断了。不加这层nginx倒是可以一直连着。
