### ISSUE TITLE
关于手册中"transport"的疑问

### ISSUE THREAD

**Issue by okaygh** [ToutyRater/v2ray-guide#26]
因为http伪装好长一串,我在客户端配了2个tcp导致json里面很长,强迫症发作想把2个一样的分连接配置http伪装合成到transport里,合完发现连不上,然后去搜手册,刚好看到dalao的注释↓

**"因为如果你在全局配置中开启了伪装功能，会导致浏览器或者其它软件无法与 V2Ray 通信！这不是 bug，只是因为你设置不当。"**

然后继续查找官方手册和dalao的手册,,始终解决不了这个问题.
我想请教dalao全局配置该如何正确开启http伪装,感谢!

**Comment by ToutyRater** [comment]
没有办法的，这是因为 transport 对所有inboun/outbound都生效，在transport设置了伪装，socks也会开启伪装的，然而浏览器的socks没有伪装功能，所以连不上。
如果你的两个outbound 都是同样的streamSetttings，那么你可以把它们合并到同一个outbound里。形如：
```javascirpt
"outbound":{
  "protocol":vmess,
  "settings":{
    "vnext":[
      {
        //此处是第一个服务器配置
      },
      {
      //第二个服务器配置
      }
    ]
     },
  "streamSettings":{
   .......
   }
}
```
在使用中这两个服务器用哪个是由v2ray决定的，用户无法控制，可能这个连接是用第一，另一个连接是用第二个。不过听说选择机制是轮循

**Comment by ToutyRater** [comment]
对于outbound，可以不填 response 的内容，inbound可以不填 request 的内容，如果有配置跟默认值一致也可以省略，这样能够有效减小配置长度

**Comment by okaygh** [comment]
@ToutyRater 即便我的inbound/inboundDetour用"http"也无法解决吗?

**Comment by okaygh** [comment]
@ToutyRater 
我是因为要本地分流才配2个服务器的,在同一个outbound如果不能指定就无奈了.
意思是客户端的outbound-response;服务端的inbound-request是可以删掉的吗?

**Comment by ToutyRater** [comment]
是可以删掉，见 https://toutyrater.github.io/advanced/httpfake.html 的示例。

我想起来了，好像是优先使用 streamSettings 的配置。也就是说在transport 全局设置伪装，然后在socks 或 http 的inbound 里设一个 streamSettings 为不伪装，这应该是可以，你试试看

**Comment by okaygh** [comment]
按照dalao的提示配置改成了这样,发现国内的网站打不开了,翻倒是没问题,一脸懵逼...
    {
    "log": {
        "loglevel": "none", 
        "access": "access.log", 
        "error": "error.log"
    }, 
    "inbound": {
        "port": 1080, 
        "listen": "127.0.0.1", 
        "protocol": "http", 
        "settings": {
            "auth": "noauth", 
            "udp": true
        }, 
        "streamSettings": {
            "network": "tcp", 
            "tcpSettings": {
                "header": {
                    "type": "none"
                }
            }
        }
    }, 
    "outbound": {
        "sendThrough": "0.0.0.0", 
        "protocol": "vmess", 
        "settings": {
            "vnext": [
                {
                    "address": "vps1", 
                    "port": 443, 
                    "users": [
                        {
                            "id": "uuid", 
                            "alterId": 64, 
                            "level": 1, 
                            "security": "aes-128-gcm"
                        }
                    ]
                }
            ]
        }, 
        "streamSettings": {
            "network": "tcp"
        }, 
        "mux": {
            "enabled": false, 
            "concurrency": 8
        }
    }, 
    "inboundDetour": [
        {
            "port": 1088, 
            "listen": "127.0.0.1", 
            "protocol": "http", 
            "settings": {
                "auth": "noauth", 
                "udp": true
            }, 
            "streamSettings": {
                "network": "tcp", 
                "tcpSettings": {
                    "header": {
                        "type": "none"
                    }
                }
            }, 
            "allocate": {
                "strategy": "always", 
                "refresh": 5, 
                "concurrency": 1
            }, 
            "tag": "download"
        }
    ], 
    "outboundDetour": [
        {
            "protocol": "freedom", 
            "settings": { }, 
            "tag": "direct"
        }, 
        {
            "protocol": "blackhole", 
            "settings": {
                "response": {
                    "type": "http"
                }
            }, 
            "tag": "blocked"
        }, 
        {
            "sendThrough": "0.0.0.0", 
            "protocol": "vmess", 
            "settings": {
                "vnext": [
                    {
                        "address": "vps2", 
                        "port": 443, 
                        "users": [
                            {
                                "id": "uuid", 
                                "alterId": 64, 
                                "level": 1, 
                                "security": "aes-128-gcm"
                            }
                        ]
                    }
                ]
            }, 
            "streamSettings": {
                "network": "tcp"
            }, 
            "tag": "downloadout", 
            "mux": {
                "enabled": false, 
                "concurrency": 1
            }
        }
    ], 
    "transport": {
        "tcpSettings": {
            "header": {
                "type": "http", 
                "request": {
                    "version": "1.1", 
                    "method": "GET", 
                    "path": [
                        "/"
                    ], 
                    "headers": {
                        "Host": [
                            "www.cloudflare.com", 
                            "www.amazon.com"
                        ], 
                        "User-Agent": [
                            "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36", 
                            "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
                        ], 
                        "Accept-Encoding": [
                            "gzip, deflate"
                        ], 
                        "Connection": [
                            "keep-alive"
                        ], 
                        "Pragma": "no-cache"
                    }
                }
            }
        }
    }, 
    "dns": {
        "servers": [
            "8.8.8.8", 
            "8.8.4.4"
        ]
    }, 
    "routing": {
        "strategy": "rules", 
        "settings": {
            "domainStrategy": "IPIfNonMatch", 
            "rules": [
                {
                    "type": "field", 
                    "ip": [
                        "0.0.0.0/8", 
                        "10.0.0.0/8", 
                        "100.64.0.0/10", 
                        "127.0.0.0/8", 
                        "169.254.0.0/16", 
                        "172.16.0.0/12", 
                        "192.0.0.0/24", 
                        "192.0.2.0/24", 
                        "192.168.0.0/16", 
                        "198.18.0.0/15", 
                        "198.51.100.0/24", 
                        "203.0.113.0/24", 
                        "::1/128", 
                        "fc00::/7", 
                        "fe80::/10"
                    ], 
                    "outboundTag": "direct"
                }, 
                {
                    "type": "field", 
                    "inboundTag": [
                        "download"
                    ], 
                    "outboundTag": "downloadout"
                }, 
                {
                    "type": "field", 
                    "domain": [
                        "geosite:cn"
                    ], 
                    "outboundTag": "direct"
                }, 
                {
                    "type": "field", 
                    "ip": [
                        "geoip:cn"
                    ], 
                    "outboundTag": "direct"
                }
            ]
        }
    }
}

**Comment by ToutyRater** [comment]
抱歉，我也不清楚为什么，爱莫能助

**Comment by okaygh** [comment]
好吧,还是谢谢dalao了...
