### ISSUE TITLE
请问v2ray 内核版 如何让终端走代理

### ISSUE THREAD

**Issue by umrwifi** [ToutyRater/v2ray-guide#30]
用的是终端启动的v2ray 设置了export ALL_PROXY=socks5://127.0.0.1:1080 /  终端还是ping 不通 google
用ss客户端这个方法是可行的  具体原理不是很懂  想让终端也走一下代理   想请教一下

**Comment by Hsiao-Jan** [comment]
解决了吗？

**Comment by zhangshen023** [comment]
解决了吗？

**Comment by umrwifi** [comment]
> 解决了吗？

其实是可以的  并不需要去设置什么

**Comment by Hsiao-Jan** [comment]
还没解决，我直接用全局代理 mac终端 ping不同google 我用v2rayu生成的终端代理命令 也ping 不同 不知道怎样弄




------------------ 原始邮件 ------------------
发件人: "umrwifi"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 晚上7:08
收件人: "ToutyRater/v2ray-guide"<v2ray-guide@noreply.github.com>;
抄送: "Vac"<1065368543@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ToutyRater/v2ray-guide] 请问v2ray 内核版 如何让终端走代理 (#30)



 
解决了吗？
  
其实是可以的  并不需要去设置什么

**Comment by painterQ** [comment]
这个issue怎么关了呢，你们都能了吗

**Comment by Hsiao-Jan** [comment]
没解决呀，是自己关闭了，我现在解决方案就是用iterm 2终端的代理方式，我试了一次是可以的，因为我主要是当时想用来拉取一些需要fq的go依赖包，用go自带的代理也蛮快的，现在需求比较少，就没怎么研究过了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: painterQ <notifications@github.com&gt;
发送时间: 2019年10月23日 14:55
收件人: ToutyRater/v2ray-guide <v2ray-guide@noreply.github.com&gt;
抄送: Hsiao_Jan <1065368543@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ToutyRater/v2ray-guide] 请问v2ray 内核版 如何让终端走代理 (#30)




这个issue怎么关了呢，你们都能了吗

**Comment by LQNew** [comment]
可以使用 proxychains 解决这个问题， https://blog.fazero.me/2015/08/31/%E5%88%A9%E7%94%A8proxychains%E5%9C%A8%E7%BB%88%E7%AB%AF%E4%BD%BF%E7%94%A8socks5%E4%BB%A3%E7%90%86/

**Comment by feizhaojun** [comment]
方法没问题，看看是不是重新load了终端配置
