### ISSUE TITLE
CDN与本机IP？

### ISSUE THREAD

**Issue by szhhq** [ToutyRater/v2ray-guide#32]
大佬您好！我配置好了WebSocket+TLS+Web+CDN，科学上网没问题，电脑上也能查到v2ray连接的是CDN节点，只是还有点疑问。我通过浏览器查询本机IP时，应该显示CDN节点的IP，还是VPS的IP？目前显示的是VPS的IP，这与通过CDN能隐藏VPS的真实IP有矛盾吗？

**Comment by ToutyRater** [comment]
1. VPS的IP
2. 不矛盾
