### ISSUE TITLE
部署了v2ray之后服务器上的wp博客无法访问了

### ISSUE THREAD

**Issue by ElderMedic** [ToutyRater/v2ray-guide#34]
你好，我在我的vultr vps上部署了v2ray之后，vps上的WordPress博客无法正常访问了，只能翻强才能访问，但是ip可以ping通，xshell也可以ssh连上服务器，感觉不是ip被强的问题，请问是不是我哪里没有设置好导致是这个问题，有没有什么办法解决？

**Comment by ToutyRater** [comment]
看描述不是V2Ray的问题。无上下文，并且对建站不熟，无法提供建议 。
