### ISSUE TITLE
v2ray的服务器可以给游戏加速吗

### ISSUE THREAD

**Issue by godmei** [ToutyRater/v2ray-guide#36]
求教

**Comment by Icarusradio** [comment]
[透明代理/路由器翻墙](https://toutyrater.github.io/app/transparent_proxy.html)

> 喜欢玩网游的朋友可能要失望了，使用 V2Ray 加速游戏效果不是很好。

**Comment by ToutyRater** [comment]
早期 V2Ray 开发的重点是为了上网，并且由于 NAT 问题并不适合玩游戏。最新的版本(v4.11.0)改进了 NAT 类型，只是我无法测试新版的改进是否如我所想。
