### ISSUE TITLE
禁止BT一文destOverride是否应包含bittorrent选项？

### ISSUE THREAD

**Issue by ihcbbs** [ToutyRater/v2ray-guide#38]
如题

**Comment by ihcbbs** [comment]
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "inbound": {
    "sniffing": {
      "enabled": true,
      **"destOverride": [
        "http",
        "tls"
      ]
    },**
    "port": 16823,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
          "alterId": 64
        }
      ]
    }
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "block"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "AsIs",
      "rules": [
        {
          "type": "field",
          "outboundTag": "block",
          "protocol": [
            "bittorrent"
          ]
        }
      ]
    }
  }
}

**Comment by ToutyRater** [comment]
不需要，按教程配置即可
