### ISSUE TITLE
为什么 WebSocket 不能搭配动态端口使用？

### ISSUE THREAD

**Issue by DarienRaymond** [ToutyRater/v2ray-guide#4]
https://github.com/ToutyRater/v2ray-guide/blob/master/advance_config/websocket.md

使用的时候出了什么错误？

**Comment by ToutyRater** [comment]
具体我并不清楚。印象中大致从 16 年 11 月开始，先后有几位网友在 Telegram 群组反映 V2Ray 设置了动态端口无法访问，直到今年初才发现是因为开启了 WS 的同时无法使用动态端口，当时 [@shelikhoo](https://github.com/xiaokangwang) 也了解了这个问题，但他并不打算修复，理由是实际情况中一个 web 服务器的端口不会时常变化。如果你想详细了解这个问题，可以与他沟通

**Comment by DarienRaymond** [comment]
哦，我知道了。这个问题已经修复了。原因是之前版本中多个 WebSocket 服务不能监听同一个路径，导致服务器端无法正常运行。现在已经没有问题了。

**Comment by ToutyRater** [comment]
已更新
