### ISSUE TITLE
客户端配置里面ip地址必须加引号！！！不然会导致服务无法启动的问题

### ISSUE THREAD

**Issue by FrankKirin** [ToutyRater/v2ray-guide#55]
自己调了一下午才发现的问题，希望作者能在guide里面加上这个特别提示....

**Comment by qakcn** [comment]
IP地址本来就只能是字符串，加引号还用说吗

> 
> 
> 自己调了一下午才发现的问题，希望作者能在guide里面加上这个特别提示....

**Comment by FrankKirin** [comment]
当然有必要，能让小白更快debug，毕竟IP地址为字符串都没爆错。文档详细全面总是没有错。

**Comment by Icarusradio** [comment]
https://www.v2ray.com/chapter_02/protocols/vmess.html
官方文档都写得很清楚了。。。
