### ISSUE TITLE
高级篇中CDN部分也许可以更清晰

### ISSUE THREAD

**Issue by ziqizh** [ToutyRater/v2ray-guide#61]
`正好 V2Ray 已经支持 HTTP/2 了，又拍云、七牛、阿里都不错，腾讯的 h2 还在内测，百度不清楚。` 这段话混淆了一个概念，目前国内CDN支持H2都指的是支持H2连接（从客户端到CDN服务器），但默认回源（从CDN服务器到目标服务器）都还是http/1.1。所以按照教程里说的配置h2 + tls + web + CDN是走不通的，而网上对这方面的解释很少。
希望能添加一段对CDN连接/回源的解释，或者之后我提交个Pull Request也行。

**Comment by Ubastic** [comment]
Such a important issue

**Comment by ziqizh** [comment]
Update: The CDN part is already been updated in the community version of the tutorial.
