### ISSUE TITLE
WebSocket+TLS+caddy方案客户端一直报错

### ISSUE THREAD

**Issue by eliasyin** [ToutyRater/v2ray-guide#63]
我之前的配置参考的是V2RAY配置指南中的[TLS一章](https://toutyrater.github.io/advanced/tls.html)，使用没有问题。今天尝试使用[WebSocket+TLS+caddy的方案](https://toutyrater.github.io/advanced/wss_and_web.html)，**客户端报错，服务器端无错误**。客户端的报错内容：

> 2019/07/31 11:09:18 [Warning] [756935591] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:20 [Warning] [3688295484] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:20 [Warning] [1702724769] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:21 [Warning] [2863789953] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:24 [Warning] [991900366] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:30 [Warning] [2049262718] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.*****.****:10000/ray):  > dial tcp **.**.**.**:10000: connectex: No connection could be made because the target machine actively refused it. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.*****.****:10000/ray):  > dial tcp **.**.**.**:10000: operation was canceled v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.*****.****:10000/ray):  > dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:34 [Warning] [3762663331] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:38 [Warning] [2124582238] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it. dial tcp **.**.**.**:443: i/o timeout dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it. dial tcp **.**.**.**:443: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:43 [Warning] [3992271906] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it. dial tcp **.**.**.**:443: operation was canceled dial tcp: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:43 [Warning] [1844546635] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed
2019/07/31 11:09:48 [Warning] [1559604368] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:443: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

### 1、服务器caddy配置：
```
www.*****.****
{
  log /var/log/caddy.log
  proxy /ray localhost:10000{
    websocket
    header_upstream -Origin
  }
}
```

### 2、服务器v2ray配置：
```json
{
  "log": {
    "loglevel": "warning",
    "error": "/var/log/v2ray/error.log"
  },
  "inbounds": [
    {
      "port": 10000,
      "listen":"127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "uuid",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```
### 3、客户端配置：
```json
{
  "log": {
    "loglevel": "warning", 
    "access": "D:\\Downloads\\v2ray-windows-64\\doc\\access.log",  
    "error": "D:\\Downloads\\v2ray-windows-64\\doc\\error.log"
  },
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "www.*****.****",
            "port": 443,
            "users": [
              {
                "id": "uuid",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/ray"
        }
      }
    }
  ]
}
```

**Comment by MassSmith** [comment]
你的配置看起来没有错，但是看出错信息，似乎是你的Caddy并没有将443端口启用。你运行一下：
sudo netstat -tunlp。查看一下，是否存在443端口。另外如果vps上有的服务商会预装apache，占用80端口，Caddy可能会无法启动成功，也就无法自动申请TLS证书，443端口也就没有服务。另外我配置Caddy时，会预先把域名解析到服务器ip上，等解析成功后，也就是在服务器上PING域名，可以返回服务器的正确IP地址，再启动Caddy。我一般习惯在Caddy的配置文件中加一个
tls xxx@xxxx.xxx（请更换为一个正确的邮箱格式，不是真实的也可以）。这个是用于申请TLS证书的邮箱地址。即：
www.*****.****
{
  log /var/log/caddy.log
  root /var/www
  tls  www@domain.com
  proxy /ray localhost:10000{
    websocket
    header_upstream -Origin
  }
}
这是我常用的配置。
总结一句话，你检查一下，Caddy是否正常运行了。一些个人经验，不一定会解决你的问题，仅供参考。

**Comment by eliasyin** [comment]
> 你的配置看起来没有错，但是看出错信息，似乎是你的Caddy并没有将443端口启用。你运行一下：
> sudo netstat -tunlp。查看一下，是否存在443端口。另外如果vps上有的服务商会预装apache，占用80端口，Caddy可能会无法启动成功，也就无法自动申请TLS证书，443端口也就没有服务。另外我配置Caddy时，会预先把域名解析到服务器ip上，等解析成功后，也就是在服务器上PING域名，可以返回服务器的正确IP地址，再启动Caddy。我一般习惯在Caddy的配置文件中加一个
> tls [xxx@xxxx.xxx](mailto:xxx@xxxx.xxx)（请更换为一个正确的邮箱格式，不是真实的也可以）。这个是用于申请TLS证书的邮箱地址。即：
> [www](http://www).*****.****
> {
> log /var/log/caddy.log
> root /var/www
> tls [www@domain.com](mailto:www@domain.com)
> proxy /ray localhost:10000{
> websocket
> header_upstream -Origin
> }
> }
> 这是我常用的配置。
> 总结一句话，你检查一下，Caddy是否正常运行了。一些个人经验，不一定会解决你的问题，仅供参考。

谢谢你的回复。根据你的提示，我感觉应该是caddy没正常运行，可是不确定问题在哪
### 1、netstat -tunlp获得的端口情况
```
tcp6       0      0 :::443                  :::*                    LISTEN      18790/v2ray
tcp6       0      0 :::2015                 :::*                    LISTEN      18701/caddy
```
### 2、关于域名解析
这个是没问题的，我现在用的就是tls加密的梯子方案
### 3、关于caddy的配置文件
加邮箱的那个配置我其实尝试过，但是没能解决问题，所以就又改回去了
### 4、附加问题
我之前看了网上很多caddy教程，其中有一个是测试caddy配置文件的指令，我运行之后它出错了，但是翻了Google上很多相关问题后，还是没能找到解决的办法，我运行的指令是：
```
caddy -agree -conf /etc/caddy/Caddyfile
```
它的输出是：
```
2019/08/08 11:44:47 /etc/caddy/Caddyfile:7 - Error during parsing: Unknown directive 'header_upstream'
```

**Comment by MassSmith** [comment]
tcp6       0      0 :::443                  :::*                    LISTEN      18790/v2ray
tcp6       0      0 :::2015                 :::*                    LISTEN      18701/caddy

这个已经显示出你的问题在哪里了，你的V2ray。占用了443端口。caddy就无法使用，也就无法自动申请证书了。

**Comment by MassSmith** [comment]
tcp6       0      0 :::443                  :::*                    LISTEN      18790/v2ray
tcp6       0      0 :::2015                 :::*                    LISTEN      18701/caddy

这个显示 ，目前443端口被v2ray占用。并未被caddy使用。你再查看v2ray的配置，如果你想使用caddy的tls证书，就要把v2ray的tls证书禁用了。
