### ISSUE TITLE
关于一个nginx配置引起的报错

### ISSUE THREAD

**Issue by taozhanzhi** [ToutyRater/v2ray-guide#67]
非常感谢：
https://toutyrater.github.io/advanced/wss_and_web.html
里的详细解释，不过我在配置的时候发现了一个错误，在客户端日志里，有类似下面的错误：
failed to dial to (wss://xxx/yyy/): 400 Bad Request: too many Host headers
经研究发现，可能跟这个问题有关：
https://stackoverflow.com/questions/38146781/how-to-set-up-nginx-as-reverse-proxy-bastion-i-have-400bad-request-too-many
然后我在您的示例nginx配置里看到：
        proxy_set_header Host $http_host;
        proxy_set_header Host $host;
确实有两个Header，我注释掉一个之后，问题解决了。是不是可以在文档里说明一下？或者把这个tip加入到常见问题里？

**Comment by ToutyRater** [comment]
已修复
