### ISSUE TITLE
Docker 部署 V2Ray的运行脚本错误

### ISSUE THREAD

**Issue by buaacse** [ToutyRater/v2ray-guide#7]
首先感谢作者的详尽文档，节省了我很多学习时间。昨天按照Docker部署V2Ray一节的指导进行操作，发现端口总是连不通，查了一天，发现是运行脚本的冒号有问题：
$ sudo docker run -d --name v2ray -v /etc/v2ray：/etc/v2ray -p 8888:8888 v2ray/official  v2ray -config=/etc/v2ray/config.json

应为

$ sudo docker run -d --name v2ray -v /etc/v2ray:/etc/v2ray -p 8888:8888 v2ray/official  v2ray -config=/etc/v2ray/config.json

望更正。

**Comment by ToutyRater** [comment]
已修正
