### ISSUE TITLE
bittorrent协议识别是不是有问题

### ISSUE THREAD

**Issue by kofxnu** [ToutyRater/v2ray-guide#76]
inbound里面开启了sniff选项
"sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
路由设置中添加了bt直连   
   { // BT 流量直连
        "type": "field",
        "protocol":["bittorrent"],
        "outboundTag": "direct"
      }
但是发现bt流量还是走了代理，用的客户端是群晖的下载套件或者qb

**Comment by ToutyRater** [comment]
BT 识别实质上就是检测数据包中是否有 BT 协议的包头，因此可能会出现这样的情况，当下载器做特殊处理，或者 BT 经过加密，则无法检测出BT协议
