### ISSUE TITLE
tproxy透明代理在N1上的cpu和内存占用异常

### ISSUE THREAD

**Issue by jackyicu** [ToutyRater/v2ray-guide#79]
![image](https://user-images.githubusercontent.com/8638384/72205756-9b79ba80-34c1-11ea-86f4-1d6939a27972.png)
感谢提供了教程, 完全按照 [透明代理(TPROXY)](https://toutyrater.github.io/app/tproxy.html )在斐讯N1上设置完成了, 发现CPU占用居然高达300%多, 内存在30% ~ 50%之间牌环, 请问是我刷的这个5.77的 Armbian 有问题吗? 还是V2ray本身的问题. Mac上的V2ray内存占用才13M. 谢谢.

**Comment by ftong2010** [comment]
我是用的Ubuntu的VM，症状一样，2个CPU全部拉满了。看error.log有大量的dns的请求。具体我也搞不清楚怎么回事
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] [4147991889] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:32811
2020/01/22 06:55:47 [Debug] [792084058] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:34361
2020/01/22 06:55:47 [Info] [4147991889] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [4147991889] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] [3362147394] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:59082
2020/01/22 06:55:47 [Debug] [2578296737] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:53893
2020/01/22 06:55:47 [Debug] [2742397519] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:54594
2020/01/22 06:55:47 [Debug] [906433379] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:41480
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] [4091209215] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:53979
2020/01/22 06:55:47 [Debug] [173251749] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:49164
2020/01/22 06:55:47 [Debug] [4237918808] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:44207
2020/01/22 06:55:47 [Info] [2560954412] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [2560954412] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [3927376098] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [3927376098] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [792084058] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [792084058] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [3362147394] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [3362147394] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [2578296737] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [2578296737] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [2742397519] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [2742397519] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [906433379] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [906433379] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [173251749] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [173251749] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53
2020/01/22 06:55:47 [Info] [4237918808] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] v2ray.com/core/transport/internet/udp: UDP original destination: udp:10.80.1.153:53
2020/01/22 06:55:47 [Debug] [3419507602] v2ray.com/core/proxy/dokodemo: processing connection from: 10.80.1.153:34765
2020/01/22 06:55:47 [Info] [3419507602] v2ray.com/core/app/dispatcher: taking detour [dns-out] for [udp:10.80.1.153:53]
2020/01/22 06:55:47 [Info] [3419507602] v2ray.com/core/proxy/dns: handling DNS traffic to udp:10.80.1.153:53

**Comment by ftong2010** [comment]
好吧，我的问题UP已经说了，不要用这个服务器做DNS服务器，我没注意到这个问题:(。把dns改成主路由之后就没事了。

**Comment by jackyicu** [comment]
谢谢，我dns指向的是主路由ip，禁用了sytemd-resolved这个服务。但是内存占用依旧是维持在50%左右，估计是程序本身对arm优化有问题。
